{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import aiohttp\n",
    "import random\n",
    "import json\n",
    "import uuid\n",
    "import asyncio\n",
    "\n",
    "import numpy as np\n",
    "from common.models.trial import Solution, Advisor, AdvisorSelection, WrittenStrategy, PostSurvey, Trial, TrialSaved, TrialError, SessionError\n",
    "from utils.process import process_solution"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\"id\":\"65c14c9c4711b3af5f4f6177\",\"active\":true,\"created_at\":\"2024-02-05T21:01:16.165000\",\"redirect_url\":\"https://app.prolific.co/submissions/complete\",\"experiment_type\":\"sim_3states_8r_v6\",\"rewrite_previous_data\":true,\"networks_path\":\"data/24_02_04\",\"seed\":1,\"n_generations\":5,\"n_ai_players\":3,\"n_sessions_per_generation\":16,\"n_advise_per_session\":5,\"n_session_tree_replications\":2,\"conditions\":[\"w_ai\",\"wo_ai\"],\"n_social_learning_blocks\":1,\"n_social_learning_networks_per_block\":4,\"n_practice_trials\":2,\"n_demonstration_trials\":4,\"simulate_humans\":false,\"social_learning_trials\":[\"observation\",\"repeat\",\"try_yourself\"],\"main_only\":true,\"session_timeout\":0.5}\n"
     ]
    }
   ],
   "source": [
    "# create new experiment\n",
    "max_participants = 20  # Number of parallel participants in simulation\n",
    "\n",
    "baseurl = \"http://0.0.0.0:5050\"\n",
    "\n",
    "url = f\"{baseurl}/admin/config\"\n",
    "\n",
    "experiment_type = 'sim_3states_8r_v6'\n",
    "\n",
    "payload = json.dumps({\n",
    "  \"active\": True,\n",
    "  \"created_at\": \"2023-10-17T09:57:36.204000\",\n",
    "  \"redirect_url\": \"https://app.prolific.co/submissions/complete\",\n",
    "  \"experiment_type\": experiment_type,\n",
    "  \"rewrite_previous_data\": True,\n",
    "  \"seed\": 1,\n",
    "  \"n_generations\": 5,\n",
    "  \"n_ai_players\": 3,\n",
    "  \"networks_path\": \"data/24_02_04\",\n",
    "  \"n_sessions_per_generation\": 16,\n",
    "  \"n_advise_per_session\": 5,\n",
    "  \"n_session_tree_replications\": 2,\n",
    "  \"conditions\": [\n",
    "    \"w_ai\",\n",
    "    \"wo_ai\"\n",
    "  ],\n",
    "  \"n_social_learning_blocks\": 1,\n",
    "  \"n_social_learning_networks_per_block\": 4,\n",
    "  \"n_practice_trials\": 2,\n",
    "  \"n_demonstration_trials\": 4,\n",
    "  \"simulate_humans\": False,\n",
    "  \"social_learning_trials\": [\n",
    "    \"observation\",\n",
    "    \"repeat\",\n",
    "    \"try_yourself\"\n",
    "  ],\n",
    "  \"main_only\": True,\n",
    "  \"session_timeout\": 0.5\n",
    "})\n",
    "headers = {\n",
    "  'Content-Type': 'application/json',\n",
    "  'Authorization': 'Basic YWRtaW46YWRtaW4='\n",
    "}\n",
    "\n",
    "response = requests.request(\"POST\", url, headers=headers, data=payload)\n",
    "\n",
    "print(response.text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "session = aiohttp.ClientSession()\n",
    "\n",
    "async def get_trial(prolific_id, experiment_type):\n",
    "    url = f\"{baseurl}/session/{experiment_type}/{prolific_id}\"\n",
    "    headers = {'Content-Type': 'application/json'}\n",
    "\n",
    "    async with session.get(url, headers=headers) as response:\n",
    "        if response.status == 200:\n",
    "            try:\n",
    "                return Trial(**await response.json())\n",
    "            except:\n",
    "                return None\n",
    "        else:\n",
    "            return None\n",
    "\n",
    "\n",
    "async def post_trial(prolific_id, trial_id, body):\n",
    "    url = f\"{baseurl}/session/{prolific_id}/{trial_id}\"\n",
    "    headers = {'Content-Type': 'application/json'}\n",
    "\n",
    "    if body is not None:\n",
    "        async with session.post(url, headers=headers, data=body) as response:\n",
    "            return response.status == 200\n",
    "    else:\n",
    "        async with session.post(url, headers=headers) as response:\n",
    "            return response.status == 200\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "from common.utils.utils import estimate_solution_score, estimate_average_player_score\n",
    "from common.models.network import Network\n",
    "\n",
    "\n",
    "networks_path = Path(\"../data/24_02_04\")\n",
    "network_data = json.load(open(networks_path / \"networks.json\"))\n",
    "solutions_myopic = json.load(open(networks_path / \"solution__myopic.json\"))\n",
    "solutions_m1 = json.load(open(networks_path / \"machine_solutions\" / \"0.json\"))\n",
    "solutions_random = json.load(open(networks_path / \"solution__random.json\"))\n",
    "networks_by_id = {n[\"network_id\"]: n for n in network_data}\n",
    "solutions_myopic_by_id = {s[\"network_id\"]: s for s in solutions_myopic}\n",
    "solutions_m1_by_id = {s[\"network_id\"]: s for s in solutions_m1}\n",
    "solutions_random_by_id = {s[\"network_id\"]: s for s in solutions_random}\n",
    "\n",
    "\n",
    "def _get_solution(network_id, solution_type):\n",
    "    network = networks_by_id[network_id]\n",
    "    # get the solution for the network\n",
    "    if solution_type == \"myopic\":\n",
    "        solution = solutions_myopic_by_id[network_id]\n",
    "    elif solution_type == \"machine\":\n",
    "        solution = solutions_m1_by_id[network_id]\n",
    "    elif solution_type == \"random\":\n",
    "        solution = solutions_random_by_id[network_id]\n",
    "    else:\n",
    "        raise ValueError(\"Invalid solution type\")\n",
    "\n",
    "    solution['moves'][0] = network['starting_node']\n",
    "    score = estimate_solution_score(Network(**network), solution['moves'], 10)\n",
    "    assert score > 0, f\"Invalid solution score: {score}\"\n",
    "\n",
    "    return Solution(**solution)\n",
    "\n",
    "\n",
    "def get_solution(network_id, state):\n",
    "    assert np.absolute(state.sum() - 1) < 0.0001, f\"Invalid state: {state}\"\n",
    "    assert np.all(state >= 0), f\"Invalid state: {state}\"\n",
    "    s_type_idx = np.random.choice(list(range(len(state))), p=state)\n",
    "    s_type = ['random', \"myopic\", \"machine\"][s_type_idx]\n",
    "    return _get_solution(network_id, s_type)\n",
    "\n",
    "\n",
    "def get_solution_evaluation(solution: Solution, network_id):\n",
    "    # get rewards\n",
    "    evaluation = process_solution(networks_by_id[network_id], solution.dict())\n",
    "    return evaluation\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "p_mypopic_init = 0.3\n",
    "max_p = 1.\n",
    "drop_rate = 0.0\n",
    "\n",
    "individual_learning_factors = (\n",
    "    (0.001, [0,0,1]),\n",
    "    (0.2, [0,1,0]),\n",
    "    (0.799, [0,0,0])\n",
    ")\n",
    "\n",
    "social_learning_factors = {\n",
    "    'optimal': (\n",
    "        (0.11, [0,0,1]),\n",
    "        (0.89, [0,0,0])\n",
    "    ),\n",
    "    'myopic': (\n",
    "        (0.11, [0,1,0]),\n",
    "        (0.89, [0,0,0])\n",
    "    )\n",
    "}\n",
    "\n",
    "social_learning_strategy = \"best\"\n",
    "\n",
    "\n",
    "def scale_state(state, change):\n",
    "    state = state + change\n",
    "    state[2] = np.minimum(state[2], max_p)\n",
    "    state[1] = np.minimum(state[1], np.minimum(1 - state[2], max_p))\n",
    "    state[0] = 1 - state[2] - state[1]\n",
    "    assert np.absolute(state.sum() - 1) < 0.0001, f\"Invalid state: {state}\"\n",
    "    assert np.all(state >= 0), f\"Invalid state: {state}\"\n",
    "    return state\n",
    "\n",
    "\n",
    "def sample_change(options):\n",
    "    p = np.array([o[0] for o in options])\n",
    "    assert np.all(p >= 0), f\"Invalid probabilities: {p}\"\n",
    "    assert np.absolute(p.sum() - 1) < 0.0001, f\"Invalid probabilities: {p}\"\n",
    "    values = np.array([o[1] for o in options])\n",
    "    change_idx = np.random.choice(list(range(len(p))), p=p)\n",
    "    change = values[change_idx]\n",
    "    return change\n",
    "\n",
    "\n",
    "def individual_learning(state):\n",
    "    change = sample_change(individual_learning_factors)\n",
    "    state = scale_state(state, change)\n",
    "    return state\n",
    "\n",
    "\n",
    "def social_learning(state, strategy):\n",
    "    change = sample_change(social_learning_factors[strategy])\n",
    "    state = scale_state(state, change)\n",
    "    return state\n",
    "\n",
    "def init_state():\n",
    "    assert p_mypopic_init <= 0.5, f\"Invalid p_mypopic_init: {p_mypopic_init}\"\n",
    "    p_mypopic = random.random() * p_mypopic_init * 2\n",
    "    state = np.array([1 - p_mypopic, p_mypopic, 0]) # [random, myopic, machine]\n",
    "    return state\n",
    "\n",
    "def handle_instruction_trial(trial, state):\n",
    "    body = None\n",
    "    return body, state\n",
    "\n",
    "def handle_individual_trial(trial, state):\n",
    "    solution = get_solution(trial.network.network_id, state)\n",
    "    state = individual_learning(state)\n",
    "    return solution.json(), state\n",
    "\n",
    "def handle_written_strategy_trial(trial, state):\n",
    "    strategy = WrittenStrategy(\n",
    "        strategy=''\n",
    "    )\n",
    "    body = strategy.json()\n",
    "    return body, state\n",
    "\n",
    "def handle_demonstration_trial(trial, state):\n",
    "    solution = get_solution(trial.network.network_id, state)\n",
    "    return solution.json(), state\n",
    "\n",
    "def handle_debriefing_trial(trial, state):\n",
    "    body = None\n",
    "    return body, state\n",
    "\n",
    "def handle_social_learning_selection_trial(trial, state):\n",
    "    advisor_selection = trial.advisor_selection\n",
    "    advisor = advisor_selection.advisor_ids\n",
    "    scores = advisor_selection.scores\n",
    "\n",
    "    if social_learning_strategy == \"best\":\n",
    "        # select the advisor with the highest score\n",
    "        max_score_idx = np.argmax(scores)\n",
    "        advisor = advisor[max_score_idx]\n",
    "    elif social_learning_strategy == \"random\":\n",
    "        # select a random advisor\n",
    "        advisor = random.choice(advisor)\n",
    "    else:\n",
    "        raise ValueError(f\"Invalid social learning strategy: {social_learning_strategy}\")\n",
    "\n",
    "    selection = Advisor(\n",
    "        advisor_id=advisor\n",
    "    )\n",
    "    body = selection.json()\n",
    "    return body, state\n",
    "\n",
    "def handle_observation_trial(trial, state):\n",
    "    solution = trial.advisor.solution\n",
    "    network_id = trial.network.network_id\n",
    "    evaluation = get_solution_evaluation(solution, network_id)\n",
    "    body = None\n",
    "    return body, state\n",
    "\n",
    "def handle_repeat_trial(trial, state):\n",
    "    solution = trial.advisor.solution\n",
    "\n",
    "    solution = trial.advisor.solution\n",
    "    network_id = trial.network.network_id\n",
    "    evaluation = get_solution_evaluation(solution, network_id)\n",
    "    if evaluation['optimal'] == 10:\n",
    "        state = social_learning(state, 'optimal')\n",
    "    elif evaluation['myopic'] > 0:\n",
    "        state = social_learning(state, 'myopic')\n",
    "\n",
    "    body = solution.json()\n",
    "    return body, state\n",
    "\n",
    "def handle_try_yourself_trial(trial, state):\n",
    "    solution = get_solution(trial.network.network_id, state)\n",
    "    state = individual_learning(state)\n",
    "    return solution.json(), state\n",
    "\n",
    "\n",
    "def handle_trial(trial, state):\n",
    "    if trial.trial_type == \"instruction\":\n",
    "        return handle_instruction_trial(trial, state)\n",
    "    elif trial.trial_type == \"individual\":\n",
    "        return handle_individual_trial(trial, state)\n",
    "    elif trial.trial_type == \"written_strategy\":\n",
    "        return handle_written_strategy_trial(trial, state)\n",
    "    elif trial.trial_type == \"demonstration\":\n",
    "        return handle_demonstration_trial(trial, state)\n",
    "    elif trial.trial_type == \"debriefing\":\n",
    "        return handle_debriefing_trial(trial, state)\n",
    "    elif trial.trial_type == \"social_learning_selection\":\n",
    "        return handle_social_learning_selection_trial(trial, state)\n",
    "    elif trial.trial_type == \"observation\":\n",
    "        return handle_observation_trial(trial, state)\n",
    "    elif trial.trial_type == \"repeat\":\n",
    "        return handle_repeat_trial(trial, state)\n",
    "    elif trial.trial_type == \"try_yourself\":\n",
    "        return handle_try_yourself_trial(trial, state)\n",
    "    else:\n",
    "        raise ValueError(f\"{trial.trial_type} is an invalid trial type\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "async def run_participant():\n",
    "    trials = []\n",
    "    prolific_id = \"sim_\" + uuid.uuid4().hex[:8]\n",
    "    state = init_state()\n",
    "    current_trial_id = None\n",
    "    while True:\n",
    "        trial = await get_trial(prolific_id, experiment_type)\n",
    "        if trial is None:\n",
    "            await asyncio.sleep(5)\n",
    "            continue\n",
    "        if trial.id == current_trial_id:\n",
    "            if trial.trial_type == \"debriefing\":\n",
    "                break\n",
    "            else:\n",
    "                raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
    "\n",
    "        if random.random() < drop_rate / 2:\n",
    "            trials = [{**t, 'dropped': True} for t in trials]\n",
    "            break\n",
    "\n",
    "        current_trial_id = trial.id\n",
    "        body, state = handle_trial(trial, state)\n",
    "        await post_trial(prolific_id, trial.id, body)\n",
    "        trial_clean = json.loads(trial.json())\n",
    "        # session_clean = json.loads(trail.session.json())\n",
    "        trials.append({'trial': trial_clean, 'prolific_id': prolific_id})\n",
    "\n",
    "        if random.random() < drop_rate / 2:\n",
    "            trials = [{**t, 'dropped': True} for t in trials]\n",
    "            break\n",
    "\n",
    "    return trials"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Unclosed client session\n",
      "client_session: <aiohttp.client.ClientSession object at 0x104c362f0>\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15795' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15794' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15792' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15802' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_b884db87 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_b884db87 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15786' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15787' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_b9e09f85 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_b9e09f85 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15791' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15784' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15785' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_99fd7b00 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_99fd7b00 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15799' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15793' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_d2d413f9 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_d2d413f9 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15797' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_947952c2 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_947952c2 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15788' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_cbf0ffa5 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_cbf0ffa5 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15796' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15789' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15801' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ValueError('Trial 10 of type demonstration of prolific id sim_3922fc30 is a duplicate')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 15, in run_participant\n",
      "    raise ValueError(f\"Trial {trial.id} of type {trial.trial_type} of prolific id {prolific_id} is a duplicate\")\n",
      "ValueError: Trial 10 of type demonstration of prolific id sim_3922fc30 is a duplicate\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16268' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16315' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16280' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16324' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-94863' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16310' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-44292' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16321' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-92571' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15950' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15800' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16252' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15790' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165371' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165118' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15798' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-160152' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-92692' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165255' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165372' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15803' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-96875' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16286' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165444' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165442' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16236' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165438' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-16318' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-15939' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165661' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165440' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165446' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165695' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165437' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165445' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165441' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-165694' coro=<run_with_limit() done, defined at /var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py:16> exception=ServerDisconnectedError('Server disconnected')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/2968865731.py\", line 18, in run_with_limit\n",
      "    new_trials = await run_participant()\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1007629223.py\", line 7, in run_participant\n",
      "    trial = await get_trial(prolific_id, experiment_type)\n",
      "  File \"/var/folders/nv/p5tx0nn545v9h6_w1wtm8cg00000gn/T/ipykernel_51880/1281044691.py\", line 7, in get_trial\n",
      "    async with session.get(url, headers=headers) as response:\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 1194, in __aenter__\n",
      "    self._resp = await self._coro\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client.py\", line 605, in _request\n",
      "    await resp.start(conn)\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py\", line 966, in start\n",
      "    message, payload = await protocol.read()  # type: ignore[union-attr]\n",
      "  File \"/Users/levinbrinkmann/repros/reward-network-iii/.venv/lib/python3.10/site-packages/aiohttp/streams.py\", line 622, in read\n",
      "    await self._waiter\n",
      "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected\n"
     ]
    },
    {
     "ename": "CancelledError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mCancelledError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[30], line 57\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m trials\n\u001b[1;32m     55\u001b[0m \u001b[38;5;66;03m# Run the main coroutine with the desired maximum number of concurrent tasks\u001b[39;00m\n\u001b[0;32m---> 57\u001b[0m trials \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m main(max_participants)\n\u001b[1;32m     59\u001b[0m \u001b[38;5;66;03m# Save trials as json\u001b[39;00m\n\u001b[1;32m     60\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mopen\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtrials.json\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mw\u001b[39m\u001b[38;5;124m'\u001b[39m) \u001b[38;5;28;01mas\u001b[39;00m f:\n",
      "Cell \u001b[0;32mIn[30], line 40\u001b[0m, in \u001b[0;36mmain\u001b[0;34m(max_concurrent_tasks)\u001b[0m\n\u001b[1;32m     37\u001b[0m     tasks\u001b[38;5;241m.\u001b[39mappend(task)\n\u001b[1;32m     39\u001b[0m \u001b[38;5;66;03m# Wait for one of the tasks to complete\u001b[39;00m\n\u001b[0;32m---> 40\u001b[0m done, _ \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m asyncio\u001b[38;5;241m.\u001b[39mwait(tasks, return_when\u001b[38;5;241m=\u001b[39masyncio\u001b[38;5;241m.\u001b[39mFIRST_COMPLETED)\n\u001b[1;32m     42\u001b[0m n_finished \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;28mlen\u001b[39m(done)\n\u001b[1;32m     44\u001b[0m \u001b[38;5;66;03m# Remove the completed tasks\u001b[39;00m\n",
      "File \u001b[0;32m/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:384\u001b[0m, in \u001b[0;36mwait\u001b[0;34m(fs, timeout, return_when)\u001b[0m\n\u001b[1;32m    377\u001b[0m     warnings\u001b[38;5;241m.\u001b[39mwarn(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe explicit passing of coroutine objects to \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    378\u001b[0m                   \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124masyncio.wait() is deprecated since Python 3.8, and \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    379\u001b[0m                   \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mscheduled for removal in Python 3.11.\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    380\u001b[0m                   \u001b[38;5;167;01mDeprecationWarning\u001b[39;00m, stacklevel\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m2\u001b[39m)\n\u001b[1;32m    382\u001b[0m fs \u001b[38;5;241m=\u001b[39m {ensure_future(f, loop\u001b[38;5;241m=\u001b[39mloop) \u001b[38;5;28;01mfor\u001b[39;00m f \u001b[38;5;129;01min\u001b[39;00m fs}\n\u001b[0;32m--> 384\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m _wait(fs, timeout, return_when, loop)\n",
      "File \u001b[0;32m/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:491\u001b[0m, in \u001b[0;36m_wait\u001b[0;34m(fs, timeout, return_when, loop)\u001b[0m\n\u001b[1;32m    488\u001b[0m     f\u001b[38;5;241m.\u001b[39madd_done_callback(_on_completion)\n\u001b[1;32m    490\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 491\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m waiter\n\u001b[1;32m    492\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    493\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m timeout_handle \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mCancelledError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "\n",
    "def check_unfinished(experiment_type):\n",
    "    BACKEND_URL = 'http://localhost:5050'\n",
    "    BACKEND_USER = 'admin'\n",
    "    BACKEND_PASSWORD = 'admin'\n",
    "    finished = False\n",
    "    url = f'{BACKEND_URL}/results'\n",
    "    headers = {'Accept': 'application/json'}\n",
    "    auth = (BACKEND_USER, BACKEND_PASSWORD)\n",
    "    sessions = requests.get(f'{url}/sessions?experiment_type={experiment_type}&finished={finished}', headers=headers, auth=auth)\n",
    "    sessions_json = sessions.json()\n",
    "\n",
    "    n_unfinished_sessions = len(sessions_json)\n",
    "    return n_unfinished_sessions\n",
    "\n",
    "\n",
    "async def run_with_limit(semaphore, trials):\n",
    "    async with semaphore:\n",
    "        new_trials = await run_participant()\n",
    "        if new_trials:\n",
    "            trials.extend(new_trials)\n",
    "\n",
    "\n",
    "async def main(max_concurrent_tasks):\n",
    "    trials = []\n",
    "    semaphore = asyncio.Semaphore(max_concurrent_tasks)\n",
    "    tasks = []\n",
    "\n",
    "    n_sessions = check_unfinished(experiment_type)\n",
    "    n_finished = 0\n",
    "    n_started = 0\n",
    "\n",
    "    # Assuming you have a way to determine if more participants should be run\n",
    "    while n_finished < n_sessions:\n",
    "        while len(tasks) < max_concurrent_tasks and n_started < n_sessions:\n",
    "            task = asyncio.create_task(run_with_limit(semaphore, trials))\n",
    "            n_started += 1\n",
    "            tasks.append(task)\n",
    "\n",
    "        # Wait for one of the tasks to complete\n",
    "        done, _ = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)\n",
    "\n",
    "        n_finished += len(done)\n",
    "\n",
    "        # Remove the completed tasks\n",
    "        tasks = [t for t in tasks if not t.done()]\n",
    "\n",
    "\n",
    "\n",
    "    # Wait for the remaining tasks to complete\n",
    "    if tasks:\n",
    "        await asyncio.wait(tasks)\n",
    "\n",
    "    return trials\n",
    "\n",
    "# Run the main coroutine with the desired maximum number of concurrent tasks\n",
    "\n",
    "trials = await main(max_participants)\n",
    "\n",
    "# Save trials as json\n",
    "with open('trials.json', 'w') as f:\n",
    "    json.dump(trials, f, indent=4)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
